name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Running Tests
      run: |
        echo Starting the tests:
        mkdir bin 
        mkdir lib 
        curl https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.5.2/junit-platform-console-standalone-1.5.2.jar -o lib/junit-file.jar
        javac -d bin/ src/Calculator.java
        javac -d bin -cp bin:lib/junit-platform-console-standalone1.5.2.jar test/*
        java -jar lib/junit-file.jar --class-path bin --scan-class-path
